on:
  pull_request:
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

name: continuous-integration

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - run: git config --global core.autocrlf false
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/checkout@v3

      - name: Install Dependencies Ubuntu
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
        if : ${{ matrix.os == 'ubuntu-22.04' }}

      - name: Install Dependencies macOS
        run: |
          brew install SDL2
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Install Dependencies Windows
        shell: bash
        run: |
          ${VCPKG_INSTALLATION_ROOT}/vcpkg install sdl2:x64-windows
        if: ${{ matrix.os == 'windows-latest' }}

      # FIXME: Restore to a proper tag on SerenityOS/setup-jakt once fix is merged
      - uses: ADKaster/setup-jakt@70e611fcdeaa18ee8787c8176920a60d8a2fb065

      - name: Configure CMake Unix
        run: |
          cmake -GNinja -B build -DCMAKE_CXX_COMPILER=clang++
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Configure CMake Windows
        shell: bash
        run: |
          cmake -GNinja -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_TOOLCHAIN_FILE="${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
        if: ${{ matrix.os == 'windows-latest' }}

      - run: cmake --build build
